[video]
VSyncEnabled = false
RenderWidth = 400
RenderHeight = 300
DisplayWidth = 800
DisplayHeight = 600
Fullscreen = 0
# If IgnoreRenderResolution is true, it will ignore your RenderWidth and RenderHeight preferences, if false, it will enforce your RenderWidth and RenderHeight preferences (which may cause stretching).
IgnoreRenderResolution = true
FieldOfView = 90
CameraNear = 0.0001

[profile]
ReportFPS = false

[input]
MouseSensitivity = 0.1
InvertVertical = false
InvertHorizontal = false
Velocity = 1.0
